/**
 * Generate `docs/openapi.yml` from the in-process zod-to-openapi registry (#143).
 *
 * Walks every `*.openapi.ts` module via `loadAllRouteSchemas()` to
 * trigger registration, then asks the registry to emit OpenAPI 3.1.
 *
 * Run locally:
 *   pnpm --filter @brandblitz/api gen:openapi              # one-shot
 *   pnpm --filter @brandblitz/api gen:openapi -- --watch   # regenerate on route change
 *   pnpm --filter @brandblitz/api dev:openapi              # same watcher, wired for dev
 *
 * `--watch` recursively `fs.watch`es `apps/api/src/routes` and, on every
 * `.ts` change, re-runs this script in a fresh child process. Respawning
 * (instead of re-importing in-process) rebuilds the module registry from
 * scratch each time, so watch-mode output is byte-identical to a one-shot run.
 *
 * CI uses this same script to detect drift — regenerates the spec
 * and diffs against the committed `docs/openapi.yml`. A non-zero
 * diff fails the workflow.
 */

import { spawn } from "node:child_process";
import { watch } from "node:fs";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { OpenApiGeneratorV31 } from "@asteasolutions/zod-to-openapi";
import { stringify as stringifyYaml } from "yaml";

import { registry, loadAllRouteSchemas } from "../src/lib/openapi-registry";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const API_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(API_ROOT, "..", "..");
const OUTPUT_PATH = resolve(REPO_ROOT, "docs", "openapi.yml");
const ROUTES_DIR = resolve(API_ROOT, "src", "routes");
const WATCH_FLAG = "--watch";
const WATCH_DEBOUNCE_MS = 250;

const HEADER = [
  "# Generated by `pnpm --filter @brandblitz/api gen:openapi` (#143).",
  "# DO NOT EDIT BY HAND. Re-run the generator and commit the diff.",
  "#",
  "# CI runs `gen:openapi:check` on every PR touching apps/api/src/routes/**",
  "# to catch route/schema changes that weren't accompanied by a regenerated",
  "# spec. If that check fails, run the command above and commit the result.",
  "",
].join("\n");

async function generate(): Promise<void> {
  await loadAllRouteSchemas();

  registry.registerComponent("securitySchemes", "bearerAuth", {
    type: "http",
    scheme: "bearer",
    bearerFormat: "JWT",
  });

  const generator = new OpenApiGeneratorV31(registry.definitions);
  const document = generator.generateDocument({
    openapi: "3.1.0",
    info: {
      title: "BrandBlitz API",
      version: process.env.npm_package_version || "0.1.0",
      description: [
        "BrandBlitz HTTP API.",
        "",
        "Spec is generated from zod schemas at `apps/api/src/routes/openapi/*.openapi.ts`",
        "via `pnpm --filter @brandblitz/api gen:openapi`. CI fails the build when the",
        "generated spec drifts from the committed `docs/openapi.yml`, so every route",
        "schema change must be accompanied by a regenerated spec in the same commit.",
      ].join("\n"),
    },
    servers: [
      { url: "https://api.brandblitz.app", description: "Production" },
      { url: "http://localhost:4000", description: "Local dev" },
    ],
  });

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, HEADER + stringifyYaml(document), "utf8");
  process.stdout.write(`wrote ${OUTPUT_PATH}\n`);
}

/**
 * Re-run this script as a one-shot child process. A fresh process means a
 * fresh module registry — dynamic imports inside `loadAllRouteSchemas()`
 * would otherwise hit the ESM module cache and register nothing on the
 * second run.
 */
function regenerateInChild(): Promise<void> {
  return new Promise((done) => {
    const child = spawn(process.execPath, ["--import", "tsx", __filename], {
      cwd: API_ROOT,
      stdio: "inherit",
      env: process.env,
    });
    child.on("error", (err) => {
      process.stderr.write(`gen-openapi watch: failed to respawn generator: ${err.message}\n`);
      done();
    });
    child.on("exit", (code, signal) => {
      if (code !== 0) {
        process.stderr.write(`gen-openapi watch: generator exited with ${signal ?? code}\n`);
      }
      done();
    });
  });
}

async function watchRoutes(): Promise<void> {
  // Initial one-shot run so the spec is fresh before we start watching.
  await generate();

  let debounce: NodeJS.Timeout | null = null;
  let running = false;
  let queued = false;

  const run = async (): Promise<void> => {
    if (running) {
      queued = true;
      return;
    }
    running = true;
    try {
      await regenerateInChild();
    } finally {
      running = false;
      if (queued) {
        queued = false;
        void run();
      }
    }
  };

  const watcher = watch(ROUTES_DIR, { recursive: true }, (_event, filename) => {
    const name =
      typeof filename === "string" ? filename : filename == null ? null : String(filename);
    // Only react to TypeScript edits — editors drop plenty of other noise.
    if (name && !name.endsWith(".ts")) return;
    if (debounce) clearTimeout(debounce);
    debounce = setTimeout(() => {
      process.stdout.write(`route change${name ? ` (${name})` : ""} — regenerating\n`);
      void run();
    }, WATCH_DEBOUNCE_MS);
  });

  process.stdout.write(`watching ${ROUTES_DIR} (recursive) — Ctrl-C to stop\n`);

  const shutdown = (): void => {
    watcher.close();
    process.exit(0);
  };
  process.once("SIGINT", shutdown);
  process.once("SIGTERM", shutdown);
}

async function main(): Promise<void> {
  if (process.argv.includes(WATCH_FLAG)) {
    await watchRoutes();
  } else {
    await generate();
  }
}

void main().catch((err) => {
  process.stderr.write(`gen-openapi failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
